### ISSUE TITLE
Add notebooks to the repo and to the docs

### ISSUE THREAD

**Issue by sylvlecl** [powsybl/pypowsybl#139]
* **Do you want to request a *feature* or report a *bug*?**

Documentation.

* **What is the current behavior?**

In current state of the repo, the only available documentation is the "readthedocs" site, together with docstrings and with the repo README.

* **What is the expected behavior?**

In order to demonstrate the use of pypowsybl on more practical use cases than in the doc, and to make it easier to try pypowsybl, let's add some example notebooks to the repository, in a `notebooks` folder.

We can make them available on [binder](https://mybinder.org/) and add links to it into the README and on the web documentation.

**Comment by geofjamg** [comment]
I gave a try to binder, indeed that would be great to have mybinder links to README. It seems to be more difficult as expected as binder seems to want to build pypowsybl before running the session (if code has changed since last binder use for this repo).
The problem is that pypowsybl build is quite complex and require to have cmake, maven, g++ and graalvm native image on the build machine.
According to binder doc it seems we have 2 solutions:
 - a pre-build bash script that would download and install everything
 - a custom docker image already prepared by ourself (not recommanded in the doc?)
What would be the best one?

**Comment by sylvlecl** [comment]
I guess we should try to only use releases on binder.
Maybe a very simple solution would be to use another repo for notebooks, which would list `pypowsybl` in its `requirements.txt`, as any other third party library. That way binder should not need to build anything.

**Comment by geofjamg** [comment]
> I guess we should try to only use releases on binder. Maybe a very simple solution would be to use another repo for notebooks, which would list `pypowsybl` in its `requirements.txt`, as any other third party library. That way binder should not need to build anything.

Good idea this is the simplest solution!

**Comment by geofjamg** [comment]
> 
> 
> I guess we should try to only use releases on binder. Maybe a very simple solution would be to use another repo for notebooks, which would list `pypowsybl` in its `requirements.txt`, as any other third party library. That way binder should not need to build anything.

Done with https://github.com/powsybl/pypowsybl-notebooks

**Comment by sylvlecl** [comment]
Closing since first notebooks have been created.
