### ISSUE TITLE
missing information for shunt

### ISSUE THREAD

**Issue by EtienneLt** [powsybl/pypowsybl#203]
* **Do you want to request a *feature* or report a *bug*?**

feature

* **What is the current behavior?**

there are missing information about shunt compensators

* **What is the expected behavior?**

bPerSection, TargetV, TargetDeadband and VoltageRegulatorOn columns should be add to the dataframe.
the update method should be modify according to the needed columns

**Comment by sylvlecl** [comment]
**Note:** 
Other data are missing : `b`, `g` (the values for the current section count), `regulating_bus_id`, and `model_type`.

**About data of the underlying model (linear or non linear):**
- **for the non linear model**, it is natural to have one more table with a multi-index (id, section_num)
- **for the linear model**, we need to choose between adding one more table too, which will be more consistent, or putting the data in the shunt table, since it has the same cardinality: it might be slightly more natural to use for users who only have linear shunts.
I am more in favor of having a separate table, to be consistent with the underlying java model. Even, then, we could add a "merge" of the 2 tables on python side if users ask for it.
@geofjamg : any opinion about this ?

**Comment by sylvlecl** [comment]
Implemented in #205 and #219.
