### ISSUE TITLE
Loadflow report

### ISSUE THREAD

**Issue by sylvlecl** [powsybl/pypowsybl#224]
* **Do you want to request a *feature* or report a *bug*?**

Feature

* **What is the expected behavior?**

powsybl loadflow API now allows to produce a report of execution through the `Reporter` API.
It will be interesting to provide access to that report to the user.

But in what form ?

- a first implementation can simply print the logs to a string and return it
- but it would be best to get a structured object/list as in java implementation

* **What is the motivation / use case for changing the behavior?**

Access to functional logs for the user:
 - file import report 
 - loadflow iterations etc. for expert users

**Comment by CBiasuzzi** [comment]
How would we change reasonably the existing APIs to include an execution report (maybe optionally)?
The current API to run an ac loadflow is:

```
def run_ac(network: _Network, parameters: Parameters = None, provider : str = 'OpenLoadFlow') 
   -> _List[ComponentResult]:
```
Example usage,  from demo.py:  
```
results = run_ac(network)
for result in results:
    print(result)
```

Among the several viable approaches:

**Option1:** we could return the report as the second element, in a tuple. 

```
def run_ac(network: _Network, parameters: Parameters = None, provider : str = 'OpenLoadFlow') 
   -> _Tuple[_List[ComponentResult], str]:
```

Example usage: 
```
result, report = run_ac(network)
for result in results:
    print(result)
print(report)
```

This breaks the current APIs' return type. Users must know that the result is a tuple and how to get the wanted 'piece' from the tuple (i.e. results = run_ac(network) does not work as expected, anymore)

**Option2**: we could have a dedicated set of APIs, to separate completely those with and without the report, e.g.

```
def run_ac(network: _Network, parameters: Parameters = None, provider : str = 'OpenLoadFlow') 
   -> _List[ComponentResult]:


def run_ac_with_report(network: _Network, parameters: Parameters = None, provider : str = 'OpenLoadFlow') 
   -> _Tuple[_List[ComponentResult], str]:
```

Option2 does not break the original APIs' return type. Example usage: 
```
result = run_ac(network)
result, report = run_ac_with_report(network)
```


**Option3:** we could return either a  _List[ComponentResult] or the previously mentioned tuple
```
def run_ac(network: _Network, parameters: Parameters = None, provider : str = 'OpenLoadFlow', withReport : bool = False) 
   -> _Union[_Tuple[_List[ComponentResult], str], _List[ComponentResult]]:
```

the function's logic, depending on the withReport parameter, returns a Tuple (results, report) or a  _List[ComponentResult]
Examples usage: 
```
result, report = run_ac(network, withReport=True)  returns a tuple
result = run_ac(network, withReport=False)  returns a _List[ComponentResult]
```
(with the withReport default = False) this does not break the current API's return type,
but, this is really a bad approach that leads to lexical ambiguities, when reading code, e.g.

```
results = pp.loadflow.run_ac(network)  #  In this case, results is a [_List[ComponentResult]
results = pp.loadflow.run_ac(network, withReport = True)   #  In this case, results is a Tuple
```

**Option 4:** we could define and return a LoadflowResults class that includes both the _List[ComponentResult] and the report

```
run_ac(network: _Network, parameters: Parameters = None, provider : str = 'OpenLoadFlow') 
    -> LoadflowResults:
```

This option  breaks the current APIs' return type, too: users must get loadflow results explicitly from a LoadflowResults instance
even if effects to users can be mitigated in some way by defining LoadflowResults as an iterable class:

```
class LoadflowResults:
    def __init__(self, component_results: _List[ComponentResult], report: str = None):
        self.component_results = component_results
        self.report = report

    def __iter__(self):
        for result in self.component_results:
                yield result
```


so that users could still write code like in the example, below:
```
    results = pp.loadflow.run_ac(big_RTE_network)
    for result in results:
        print(result)
	print(result.report)
```
	
The above examples are built on the run_ac function, but the issue also applies to other pypowsybl APIs that could be extended to return a functional log, e.g.
`   network = pp.network.load(NETWORK_PATH)`

  
What is your opinion? Are there other options that fit Python, better?

**Comment by geofjamg** [comment]
@CBiasuzzi thanks you for the analysis. Not easy to decide as there is no perfect solution.
I don't like the method overload `run_ac_with_report`, this is the only correct solution to not break the API but it clutters the API and as a long term vision of the API it seems to me to not be a good idea
Probably 4 is the cleanest solution (the one we would have chosen if report have been part of the design from start) but it breaks the API compatibility: Maybe it is still the best solution.

It raises a very good question regarding pypowsybl (and I don't have the answer...): we have more and more users that write more and more code. By breaking APIs, do we risk to lost/angry some of our users or is it fair with some documentation from time to time to make breaking change in order to keep compatibility? @sylvlecl @EtienneLt @annetill

**Comment by AnkurArohi** [comment]
@geofjamg regarding API I would also like to bring in my suggestions 

From my point of view it is important to not change the API very often, so if it makes sense use different special parameter for API function with a slightly different feature or usability.
So not to use function overloading but actually change the parameter list still having by default the original API call possible.

Ex. run_ac(...,...,...,with_report=False)

In this way you keep old users happy and parallel also allow new features/enrichment to be built

**Comment by sylvlecl** [comment]
> Probably 4 is the cleanest solution (the one we would have chosen if report have been part of the design from start) but it breaks the API compatibility: Maybe it is still the best solution.

Would we change the import API in the same way ?
```python
import_result = pn.read('network.xiidm')
network = import_result.network
report = import_result.report
# or with a tuple
network, report = pn.read('network.xiidm')
```
It's a quite important breaking change since basically everybody who uses the lib today must use it.

Or, we could include the report in the network object ... : 
```python
network = pn.read('network.xiidm')
report = network.import_report
```

it may not be too bad in that case, it's really an immutable property of the network.

> So not to use function overloading but actually change the parameter list still having by default the original API call possible.

One issue with this approach is that it can be inconvenient/weird if your return type depends on the arguments:
```python
network = pn.read('network.xiidm', with_report=False)  # OK
network = pn.read('network.xiidm', with_report=True)  # Does not work any more! we get a tuple, not a network
```

**Comment by sylvlecl** [comment]
For the loadflow result, it seems indeed the way to go to switch to a global `LoadFlowResults` object, returning a list like today does not leave enough place for future evolutions.

With one result class, we will be able to add any property we like in the future.

**Comment by AnkurArohi** [comment]
> For the loadflow result, it seems indeed the way to go to switch to a global `LoadFlowResults` object, returning a list like today does not leave enough place for future evolutions.
> 
> With one result class, we will be able to add any property we like in the future.

What about using a default boolean as I mentioned above

**Comment by geofjamg** [comment]
> > For the loadflow result, it seems indeed the way to go to switch to a global `LoadFlowResults` object, returning a list like today does not leave enough place for future evolutions.
> > With one result class, we will be able to add any property we like in the future.
> 
> What about using a default boolean as I mentioned above

This is dangerous and not a clean design to change return type depending of a parameter

**Comment by sylvlecl** [comment]
@CBiasuzzi @massimo-ferraro  @geofjamg 
About that issue, after all the discussions above I am changing my mind ...

Since the beginning, we have chosen (myself in the first place) to not mimic the java API where the reporter is provided as an additional argument. The main argument was that it did not seem "pythonic" enough, or not simple enough, with arguments that are mutable.

Following the discussions above, finally adding a "reporter" argument to methods does not seem that bad ...
Actually it would have some added value : it would enable, like on the java side, to produce a consolidated report for a whole process (that was one argument raised by @CBiasuzzi and @massimo-ferraro).

Plus, passing consumer arguments does not seem so unusual in python, for example all "file objects" work this way:
```python
with open('file', mode='wb') as f:
    df.to_csv(f)
```

So an interface like this could be nice to use and raise less questions about breaking changes etc:

```python
reporter = pp.report.Reporter()  # creates a ReporterModel behind the scene
network = pp.network.load('file.xiidm', reporter=reporter)
res = pp.loadflow.run_ac(network, reporter=reporter)

print(str(reporter))  # the report printed as text
json_report = reporter.to_json()  # serializes to json
```

At least in a first place, the report would be an opaque object with only print/serialization features.
We could also expose its content as a dict, for example by simply loading the json as a dict.

Does it seem OK ?

**Comment by geofjamg** [comment]
Perfect!

**Comment by sylvlecl** [comment]
PS:
possibly in a further evolution, we could enable to write to the reporter from python, and create sub reporters (nice to structure the report for a complex python process)
