### ISSUE TITLE
Modifying/adding properties on network elements

### ISSUE THREAD

**Issue by nicolaslhuillier** [powsybl/pypowsybl#328]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
Though optional attributes can be retrieve in element dataframes (via get_XXX() functions, e.g. 'get_generators(True)'),
it is currently only possible to modify IIDM attributes (via update_XXX() functions).
Attempt to modify an existing property YYY raises the error message :"no column named YYY"
 
* **What is the expected behavior?**
It would be very useful to be able to modify attributes that are not part of core IIDM (e.g. "property" or "extension").
If the attribute does not exist, it could even be added as a new property.

* **What is the motivation / use case for changing the behavior?**
The use-case is to attach custom information to network elements in order to ease further processing (e.g. time-series mapping)

**Comment by sylvlecl** [comment]
For the handling of arbitrary properties, it would be better to not mix the creation of properties with `update_***` methods, because it will be error-prone: the user can easily end up creating new columns whereas he wanted to update an existing one.

For this reason, I would propose to have a separate method:
```python
network.add_elements_properties(id=['GEN1', 'GEN2'], my_prop=['value1', 'value2'])
```

Then for removal:
```python
network.remove_elements_properties(properties=['my_prop'], id=['GEN1', 'GEN2'])
```

Eventually, it raises the question of properties handling in getters:
to keep consistent, we could remove those columns from the usual `get_***` methods,
and have a unique `get_elements_properties` method, similarly to extensions handling.

Obviously this would be a breaking change. However this would clarify an ambiguity around properties,
where users may be surprised that some data are strings (see #199). It would also avoid
the inflation of dataframe columns.

Any opinion on this proposition @geofjamg @nicolaslhuillier @EtienneLt @vincentbarbesant ?

**Comment by geofjamg** [comment]
Fully agree with the proposition but only worried about the breaking change.
Maybe as an intermediate version properties could be duplicated in both the element table and the property one ? And then remove them from element table next version?
With a warning when gettting a table with properties to force the user to migrate?

**Comment by nicolaslhuillier** [comment]
I also agree it is better to distinguish between "update" and "add".
I understand the point on "getters", but from a user's perspective it is more convenient if iidm attributes, properties and extensions all come directly in the same dataframe (without the need of a merge)

**Comment by sylvlecl** [comment]
Indeed the consequence of removing from the existing table would be to force the user to have wrapper methods such as:

```python
def get_lines_with_my_prop(network: Network) -> pd.DataFrame:
    lines = network.get_lines()
    props = getwork.get_elements_properties('my_prop', id=lines.index)
    return lines.join(props)
```

Maybe it's OK to keep both mechanisms even in the long run? The drawbacks would be:
- the unclear difference between properties and other columns, with consequence in particular on typing (strings only)
- the fact that the user may be surprised to not be able to update those columns like others
- the inconsistency with extensions handling

I cannot say they are major ones.

In any case, we can start by only adding the new add/remove methods.

**Comment by geofjamg** [comment]
Maybe just a addProperties to the get_lines() but indeed without having the possibility to modify it.

**Comment by sylvlecl** [comment]
The `add_elements_properties` and `remove_elements_properties` have been implemented, and properties are left as columns in the network elements dataframes.
