### ISSUE TITLE
Casting from Python instance to C++ fails to generate pypowsybl df

### ISSUE THREAD

**Issue by AnkurArohi** [powsybl/pypowsybl#417]
* **Do you want to request a *feature* or report a *bug*?**

Bug

* **What is the current behavior?**
    return _pp.create_dataframe(columns_values, columns_names, columns_types, is_index)
RuntimeError: Unable to cast Python instance to C++ type (compile in debug mode for details)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem***

a = pypowsybl.network.create_empty()

net.bus = net.bus.rename(columns={'vn_kv': 'v_mag'})

u = pd.concat([a.get_buses(True),net.bus])
Here you will also get other errors which are because there are certain columns like v_mag,v_angle which can surprisingly not be provided to pypowsybl as input directly
you need to drop them like
u.drop("zone",axis=1,inplace=True)
a.create_buses(u)

* **What is the expected behavior?**

The pypowsybl bus df should be created

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by AnkurArohi** [comment]
This issue relates to the issue :  https://github.com/powsybl/pypowsybl/issues/356 
We need good error messages to really understand what the issue is without debugging

**Comment by sylvlecl** [comment]
I think that issue is solved (see #356): we now provide a useful, understandable error message when the input data does not match the expected type.

However there was another feature request in your text, which is to be able to perform at once the 2 steps `create_buses` (which cannot set voltage magnitude, in particular) and `update_buses` (which allows to set voltage magnitude).

Should we close this one and open another one for that feature request?

**Comment by AnkurArohi** [comment]
Sorry @sylvlecl for delayed response yes sure we want simultaneous creation and updation of the bus
