### ISSUE TITLE
Error while installing pypowsybl in Raspberry Pi

### ISSUE THREAD

**Issue by suresh-iitr** [powsybl/pypowsybl#493]
* **Do you want to request a *feature* or report a *bug*?**
I am trying to install pypowsybl using the command pip install pypowsybl in Raspberry pi, os: Ubunutumate 20.04, focal, aarch64 architecture.

I am getting error , when the step running python wheels for setup.py

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  - PowSyBl Version: ...
  - OS Version: ...

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, spectrum, etc)

(if a question doesn't apply, you can delete it)

**Comment by geofjamg** [comment]
We do not provide a Linux ARM64 wheel (mainly because there is no Github Action runner for this architecture and no cross compilation support in GraalVM native image). However, even if never tested it should be possible to build the wheel yourself (using the right GraalVM Linux ARM distribution): https://github.com/powsybl/pypowsybl#build-from-sources.

**Comment by geofjamg** [comment]
GraalVM native image cross compilation support seems to be planned but with no date specified:
https://github.com/oracle/graal/issues/407#issuecomment-1188978769
